CREATE TABLE users
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
name VARCHAR(30) NOT NULL,
email VARCHAR(50),
CONSTRAINT users_key PRIMARY KEY (id)
) ;

CREATE TABLE events
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
name VARCHAR(100) NOT NULL,
price INTEGER,
rating VARCHAR(100),
CONSTRAINT events_key PRIMARY KEY (id)
) ;

CREATE TABLE eventitems
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
eventid INTEGER,
auditoriumid VARCHAR(100),
datetime BIGINT,
CONSTRAINT eventitems_key PRIMARY KEY (id)
) ;

CREATE TABLE tickets
(
id INTEGER NOT NULL GENERATED ALWAYS AS IDENTITY (START WITH 1, INCREMENT BY 1),
userid INTEGER,
seat INTEGER,
eventitemid INTEGER,
CONSTRAINT ticketss_key PRIMARY KEY (id)
) ;